### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by MarilenaRoque**
# Project Set Up Completed ✔️  :rocket:

 - Initiate Documentation
 - Initiate React Application
 - Set the main tools (Redux, React-Redux, Redux Toolkit, and NPM)
 - Add prop-types as a dependency
 - Deploy the application: [DEMO LINK](https://booksmagic.herokuapp.com/)

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @MarilenaRoque :hand: 
Great job on this milestone so far :clap: 
But we need to make some changes before moving on :smile: 

- [x] Awesome job on the README file. But we need to fix the Project title, which right now it's from the Calculator app.
- [x] It seems the linter was not properly setup. We need to follow the instructions [here](https://github.com/microverseinc/linters-config/tree/master/react-redux) and set up the linter properly.

Happy coding :computer: 
**Sergio Torres**

**Comment by MarilenaRoque** [comment]
# Thank you for the review, @Torres-ssf! :rocket:

### All the changes required are completed. ✔️ 

- The title on README.md is fixed 😅 
- The linters config was made.

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
Great job implementing the suggested changes.

**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by MarilenaRoque** [comment]
Thank you @wathigo! 👍🏻

**Pull request merged**
